<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-08-29 20:30

import django.contrib.auth.models
import django.contrib.auth.validators
=======
# Generated by Django 4.0.3 on 2022-08-22 23:29

>>>>>>> Matthew-branch
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(null=True)),
            ],
        ),
    ]
