# Generated by Django 4.0.3 on 2022-09-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account_rest", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="censored",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
