# Generated by Django 4.0.3 on 2022-08-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
