# Generated by Django 4.0.3 on 2022-08-24 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0002_accountvo_first_name_accountvo_last_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountVO',
            new_name='Account',
        ),
    ]
