# Generated by Django 4.0.3 on 2022-08-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0002_accountvo_first_name_accountvo_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvo',
            name='password',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='accountvo',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
