# Generated by Django 4.0.3 on 2022-08-23 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0003_alter_accountvo_password_alter_accountvo_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountvo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
