# Generated by Django 4.0.3 on 2022-08-23 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0004_alter_accountvo_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountVO',
            new_name='Account',
        ),
    ]
