# Generated by Django 4.0.3 on 2022-08-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0005_rename_accountvo_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
