# Generated by Django 4.0.3 on 2022-08-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_rest', '0007_alter_account_options_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(null=True),
        ),
    ]
