FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
CMD /wait && python manage.py migrate && python manage.py runserver "0.0.0.0:8000"