volumes:
    yovies-data:
        external: true
services:
    database:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - yovies-data:/var/lib/postgresql/data
        environment:
            - POSTGRES_MULTIPLE_DATABASES=movies,reviews,accounts
            - POSTGRES_PASSWORD=test-databases
        ports:
            - 15432:5432
    movie-api:
        build:
            context: ./movies/api
            dockerfile: ./Dockerfile.dev
        ports:
            - "8100:8000"
        volumes:
            - ./movies/api:/app
        environment:
            DATABASE_URL: postgresql://user-name:password@postgres/db-name
            WAIT_HOSTS: postgres:5432
    account-api:
        build:
            context: ./accounts/api
            dockerfile: ./Dockerfile.dev
        ports:
            - "8080:8000"
        volumes:
            - ./accounts/api:/app
        depends_on:
            - database
        environment:
            DATABASE_URL: postgresql://user-name:password@postgres/db-name
            WAIT_HOSTS: postgres:5432