# Generated by Django 4.0.3 on 2022-08-23 02:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('plot', models.TextField()),
                ('year', models.DateField()),
                ('rated', models.CharField(max_length=100)),
                ('released', models.DateTimeField(blank=True, null=True)),
                ('runtime', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=50)),
                ('poster', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='post',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AlterField(
            model_name='review',
            name='imdb_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='reviews_rest.movie'),
        ),
        migrations.DeleteModel(
            name='MovieVO',
        ),
    ]
