# Generated by Django 4.0.3 on 2022-09-20 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post',
            field=models.TextField(default='*'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='nothing', max_length=200),
        ),
    ]
