# Generated by Django 4.0.3 on 2022-09-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0003_alter_review_post_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
