# Generated by Django 4.0.3 on 2022-08-23 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0006_alter_review_imdb_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rated',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='released',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='runtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='source',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='value',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
