# Generated by Django 4.0.3 on 2022-08-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0008_remove_movie_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='imdb_id',
            new_name='movie_id',
        ),
    ]
