# Generated by Django 4.0.3 on 2022-08-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0009_rename_imdb_id_review_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='movie_id',
            new_name='movie',
        ),
    ]
