# Generated by Django 4.0.3 on 2022-08-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0009_remove_review_imdb_id_remove_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Review', to='reviews_rest.uservo'),
            preserve_default=False,
        ),
    ]
