# Generated by Django 4.0.3 on 2022-08-28 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_rest', '0010_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
